### PR TITLE
Fix a race that can occur if a subprocess forks and issues a syscall

### PR DESCRIPTION
**Pull request by travitch**
It seems like, in this case (which is not very rare), the forked process issues
a system call (likely an exec) before the event processing loop can process the
pseudo-STOP event after the attach.  This causes the "impossible" case to
trigger.  To fix that, just assume that if we are in this case that we are
entering a syscall stop (and not exiting a syscall stop).  This should be the
case, because we won't actually miss any real events (so syscall enter must
precede syscall exit).

### CODE REVIEW

**Comment by travitch** [comment]
I'm not 100% sure on this one, but I've observed this crash while tracing a process that forks a lot of subprocesses.  For now, all I can say is that this fix seems to work.

**Comment by ranweiler** [comment]
Thanks @travitch, I'll repro and test this locally.

**Comment by travitch** [comment]
If you are looking for an easy way to trigger it, I've been tracing invocations of `make`, which seemed to do it pretty reliably

**Comment by travitch** [comment]
Actually, I can just point you to the codebase: https://github.com/travitch/build-bom

The Cargo.toml file is currently pointing to my fork with that patch merged, so you should be able to reproduce it easily if you just remove that line

**Comment by ranweiler** [comment]
Looks like tracing this bash script can repro very consistently, too:
```bash
#!/usr/bin/env bash
for i in $(seq 100); do
  ( sleep 1; echo ) &
done
```

**Comment by ranweiler** [comment]
Digging in, it looks like the root cause is that we sometimes see the attach-stop _before_ we see `PTRACE_EVENT_FORK`. Via the test shell script above, I can get into a [different](https://github.com/ranweiler/pete/blob/master/src/ptracer.rs#L421) "unreachable" case, even with your change.

If we receive a `SIGSTOP` for a non-tracee, I think we need set its (initial!) internally-known state to `Traced` at that time. The `Attaching` state exists only to let us remember "we saw that we have a new tracee (due to fork/clone/&c), so the next `SIGSTOP` for that tracee is an attach-stop". Then, when we get the `PTRACE_EVENT_FORK` later on, we need to only set the tracee state to `Attaching` _if unset_, or else leave it be.

Your change might be good anyway, though I'm not 100% sure we want to take it if we fix the above. Getting this wrong can screw up our view of whether we're in a syscall-enter vs. exit, so I'd want to validate it some more.

I'll open a PR to handle the out-of-order eventing, and think on this some more.

**Comment by travitch** [comment]
Thanks for looking into it! I think that makes sense.

When I was hacking on that change I definitely did not fully understand the state machine model.

**Comment by ranweiler** [comment]
@travitch, if you want to smoke-test the branch in #12 against `build-bom`, I'll merge it and publish an update after that.

**Comment by travitch** [comment]
It looks like it works, thanks for the fix!

**Comment by ranweiler** [comment]
@travitch, the fix for this issue is now published as 0.3.1.

**Pull request closed without merging**
